title: cathryn stenson
logo: /assets/img/cathryn.jpg
description: personal site
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
twitter_url: https://twitter.com/cathryn_stenson
instagram_url: https://instagram.com/cathryn_stenson_art
